name: mrl
margin: 2.0 # cifar 2.0/ tiny 1.0
alpha: 0.1 #0.1
num_classes: 10 # cifar10 10  tiny 200
ignore_index: -100

object:
  _target_: calibrate.losses.RankMixup_MRL 
  margin: ${loss.margin}
  alpha: ${loss.alpha}
  num_classes: ${loss.num_classes}
  ignore_index: ${loss.ignore_index}

