name: resnet50
num_classes: 10
pretrained: False
has_dropout: False

object:
  _target_: calibrate.net.resnet.build_resnet
  encoder_name: ${model.name}
  num_classes: ${model.num_classes}
  pretrained: ${model.pretrained}
  has_dropout: ${model.has_dropout}