hydra:
  run:
    dir: /workspace/log/calib_outputs/${data.name}/${model.name}-${loss.name}-${optim.name}/${now:%Y%m%d-%H:%M:%S-%f}

defaults:
  - data: cifar10 
  - model: resnet50_cifar
  - loss: ce
  - optim: sgd
  - scheduler: multi_step
  - wandb: my
  - override hydra/job_logging: custom
  - _self_

task: cv #cv segment
device: cuda:0
seed: 
log_period: 10
train:
  clip_grad_norm: True
  max_epoch: 200
  resume: False 
  mixup: True #RankMixup
  keep_checkpoint_num: 1
  keep_checkpoint_interval: 500
calibrate:
  num_bins: 15
  visualize: False
test:
  checkpoint: ""
  save_logits: False
  post_temperature: False
wandb:
  enable: False